### ISSUE TITLE
Python2.6 incompatibility in the Configuration module (loading with CMSSW python) 

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9835]
**Impact of the bug**
WMAgent

**Describe the bug**
While validating 1.3.6.patch2, there is this old workflow using `slc5_amd64_gcc462` and a python2.6 release:
amaltaro_ReRecoSkim_Agent136_Val_200711_123408_805

it failed while applying the PSet tweaks, with:
```
AttributeError: 'tuple' object has no attribute 'major'
```

**How to reproduce it**
Run the same workflow template

**Expected behavior**
The Configuration module needs to be compatible with python 2.6, 2.7 and 3+, otherwise jobs might fail during runtime.
There might be a longer term fix coming in the next months, when the PSet tweak will be an external tool (outside of WMCore)...

**Additional context and error message**
Traceback from wmstats:
```
cmsRun1

    SCRAMScriptFailure (Exit Code: 50513)

        SCRAM scripts failed to run!
        <@========== WMException Start ==========@>
        Exception Class: PreScriptScramFailure
        Message: Error running command
        /cvmfs/cms.cern.ch/COMP/slc6_amd64_gcc493/external/python/2.7.13/bin/python2 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 

        5
         
                Scram Command Diagnostic:
                Command : scramv1
                Architecture: slc5_amd64_gcc462
                Executed: /cvmfs/cms.cern.ch/slc5_amd64_gcc462/cms/cmssw-patch/CMSSW_5_3_7_patch5/external/slc5_amd64_gcc462/bin/python2.6 -m WMCore.WMRuntime.ScriptInvoke WMTaskSpace.cmsRun1 SetupCMSSWPset 

                Exit Status: 5
                Stdout: Traceback (most recent call last):
          File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/python/2.6.4/lib/python2.6/runpy.py", line 122, in _run_module_as_main
            "__main__", fname, loader, pkg_name)
          File "/cvmfs/cms.cern.ch/slc5_amd64_gcc462/external/python/2.6.4/lib/python2.6/runpy.py", line 34, in _run_code
            exec code in run_globals
          File "/srv/job/WMCore.zip/WMCore/WMRuntime/ScriptInvoke.py", line 22, in <module>
          File "/srv/job/WMCore.zip/WMCore/WMRuntime/Bootstrap.py", line 18, in <module>
          File "/srv/job/WMCore.zip/WMCore/FwkJobReport/Report.py", line 17, in <module>
          File "/srv/job/WMCore.zip/WMCore/Configuration.py", line 17, in <module>
        AttributeError: 'tuple' object has no attribute 'major'

                Stderr: None 
        	ModuleName : WMCore.WMSpec.Steps.WMExecutionFailure
        	MethodName : __init__
        	ClassInstance : None
        	FileName : /srv/job/WMCore.zip/WMCore/WMSpec/Steps/WMExecutionFailure.py
        	ClassName : None
        	LineNumber : 18
        	ErrorNr : 50513
```

**Comment by amaltaro** [comment]
@mapellidario Dario, could you please work on this issue and find the py2.6/py2.7/py3+ compatible way of evaluating the major python version? Code to be updated is:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Configuration.py#L17

It loooks like we will need it for tomorrow morning or so (backported to the wmagent branch).

**Comment by mapellidario** [comment]
This may be easier than expected.

https://docs.python.org/3/library/sys.html#sys.version_info

"A **tuple** containing the five components of the version number,  [...]". Despite they started using a class to represent the version info in python3, this can still be accessed as a tuple, so that is has a similar interface as in python2.6.

How does `sys.version` work in py2.6

```python
> python
Python 2.6.4 (r264:75706, Feb  7 2012, 16:03:40) 
[GCC 4.6.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> type(sys.version_info)
<type 'tuple'>
>>> sys.version_info
(2, 6, 4, 'final', 0)
>>> sys.version_info[0]
2
>>> sys.version_info > (2,6,3)
True
>>> sys.version_info > (2,6,4)
True
>>> sys.version_info >= (2,6,4)
True
>>> sys.version_info > (2,6,5)
False
```

They changed this since python2.7: https://docs.python.org/release/2.7/whatsnew/2.7.html

> The sys.version_info value is now a named tuple, with attributes named major, minor, micro, releaselevel, and serial. (Contributed by Ross Light; issue 4285.)

How does it work in python2.7

```python
> python2
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> type(sys.version_info)
<type 'sys.version_info'>
>>> sys.version_info
sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)
>>> sys.version_info[0]
2
>>> sys.version_info > (2,6)
True
>>> sys.version_info > (2,7,13)
True
>>> sys.version_info >= (2,7,13)
True
>>> sys.version_info > (2,7,14)
False
```

How does it work in python3 (same as python2.7)

```python
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> type(sys.version_info)
<class 'sys.version_info'>
>>> sys.version_info[0]
3
>>> sys.version_info > (3,0)
True
>>> sys.version_info > (3,5,3)                                                                                                                               
True
>>> sys.version_info >= (3,5,3)
True
>>> sys.version_info > (3,5,4)
False                                                                                                                                                         
>>> sys.version_info >= (3,6)
False
```

I propose to change `Configuration.py`

```python
-    PY3 = sys.version_info.major == 3
+    PY3 = sys.version_info[0] == 3
```

I will open a PR with the proposed change

**Comment by amaltaro** [comment]
Thanks Dario! This is what was implemented in the future python package, but I decided to make things more clear with the attribute name :-(
