### PR TITLE
renamed ReqMgrAux method name called from DrainStatusPoller - wmagent branch

### LINKED ISSUE #9297: AgentStatusWatcher fails with AttributeError 'updateAgentConfig' on 1.2.2 agents
After the hypervisor reboot, all agents were brought back but it looks like there is a bug with AgentStatusWatcher while updating the agent config, see error here [1].

There are a few agents down, one of them is vocms0253. Bug was introduced in https://github.com/dmwm/WMCore/pull/9255

and it seems to have been fixed in master already.

[1]
```
2019-07-18 10:46:28,804:140239124489984:INFO:DrainStatusPoller:Enabling EnableAllSites flag: Updating agent to submit to all sites.
2019-07-18 10:46:28,804:140239124489984:ERROR:DrainStatusPoller:Error occurred, will retry later:
'ReqMgrAux' object has no attribute 'updateAgentConfig'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/DrainStatusPoller.py", line 56, in algorithm
    self.updateAgentSpeedDrainConfig(thresholdsHit)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/DrainStatusPoller.py", line 113, in updateAgentSpeedDrainConfig
    self.reqAuxDB.updateAgentConfig(self.config.Agent.hostName, self.agentConfig)
AttributeError: 'ReqMgrAux' object has no attribute 'updateAgentConfig'
2019-07-18 10:46:28,829:140239124489984:INFO:BaseWorkerThread:DrainStatusPoller took 0.941 secs to execute
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9297 

#### Status
ready

#### Description
One of the patches applied to the 1.2.2 agents had a method rename, and I missed it in the DrainStatusPoller. 

#### Is it backward compatible (if not, which system it affects?)
no

#### Related PRs
It complements PR https://github.com/dmwm/WMCore/pull/9255

#### External dependencies / deployment changes
no

### CODE REVIEW

**Comment by amaltaro** [comment]
[Fix #9298 - renamed ReqMgrAux method name called from DrainStatusPoller](https://trello.com/c/Tny4FP7Y/174-fix-9298-renamed-reqmgraux-method-name-called-from-drainstatuspoller)

**Comment by amaltaro** [comment]
All the old 1.2.2 agents have been patched.

**Review by todor-ivanov — APPROVED** [review]
Looks good to me!
