### PR TITLE
Fix status REST API for ReqMgr2MS

### LINKED ISSUE #9318: ReqMgr2MS status API broken
It turns out I removed the `status` method on this PR:
https://github.com/dmwm/WMCore/pull/9296/files?file-filters%5B%5D=.py#diff-453996f14095b65d84d7db2d10e0260bL302

which makes the `/microservice/data/status` hit a `500 Internal Server Error`, as in the traceback below:
```
[01/Aug/2019:02:00:52] vocms0731.cern.ch 127.0.0.1 "GET /microservice/data/status HTTP/1.1" 500 Internal Server Error [data: 344 in 742 out 2276 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
[01/Aug/2019:02:01:22]  SERVER OTHER ERROR __builtins__.AttributeError 3644ca5546ee3fe2af818f564ba8e2b8 ('MSManager' object has no attribute 'status')
[01/Aug/2019:02:01:22]    Traceback (most recent call last):
[01/Aug/2019:02:01:22]      File "/data/srv/beHG1908d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.1.2.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 723, in default
[01/Aug/2019:02:01:22]        return self._call(RESTArgs(list(args), kwargs))
[01/Aug/2019:02:01:22]      File "/data/srv/beHG1908d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.1.2.pre3/lib/python2.7/site-packages/WMCore/REST/Server.py", line 804, in _call
[01/Aug/2019:02:01:22]        obj = apiobj['call'](*safe.args, **safe.kwargs)
[01/Aug/2019:02:01:22]      File "/data/srv/beHG1908d/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.1.2.pre3/lib/python2.7/site-packages/WMCore/MicroService/Service/Data.py", line 91, in get
[01/Aug/2019:02:01:22]        res.update({'results': dict(status=self.mgr.status())})
[01/Aug/2019:02:01:22]    AttributeError: 'MSManager' object has no attribute 'status'
[01/Aug/2019:02:01:22] vocms0731.cern.ch 127.0.0.1 "GET /microservice/data/status HTTP/1.1" 500 Internal Server Error [data: 344 in 742 out 3008 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
```

### PR DESCRIPTION
**Pull request by amaltaro**
Fixes #9318 

#### Status
ready

#### Description
Put the `status` method back to the MSManager such that we can get the `status` REST API working again. I have also added some extra information to the results, until the service commissioning phase is over and we can re-purpose that API.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
Complement/fix bug introduced by https://github.com/dmwm/WMCore/pull/9296

#### External dependencies / deployment changes
no

### CODE REVIEW

**Review by vkuznet — APPROVED** [review]
fine with me
