### ISSUE TITLE
AgentStatusWatcher fails with AttributeError 'updateAgentConfig' on 1.2.2 agents

### ISSUE THREAD

**Issue by amaltaro** [dmwm/WMCore#9297]
After the hypervisor reboot, all agents were brought back but it looks like there is a bug with AgentStatusWatcher while updating the agent config, see error here [1].

There are a few agents down, one of them is vocms0253. Bug was introduced in https://github.com/dmwm/WMCore/pull/9255

and it seems to have been fixed in master already.

[1]
```
2019-07-18 10:46:28,804:140239124489984:INFO:DrainStatusPoller:Enabling EnableAllSites flag: Updating agent to submit to all sites.
2019-07-18 10:46:28,804:140239124489984:ERROR:DrainStatusPoller:Error occurred, will retry later:
'ReqMgrAux' object has no attribute 'updateAgentConfig'
Traceback (most recent call last):
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/DrainStatusPoller.py", line 56, in algorithm
    self.updateAgentSpeedDrainConfig(thresholdsHit)
  File "/data/srv/wmagent/v1.2.2.patch2/sw/slc7_amd64_gcc630/cms/wmagent/1.2.2.patch2/lib/python2.7/site-packages/WMComponent/AgentStatusWatcher/DrainStatusPoller.py", line 113, in updateAgentSpeedDrainConfig
    self.reqAuxDB.updateAgentConfig(self.config.Agent.hostName, self.agentConfig)
AttributeError: 'ReqMgrAux' object has no attribute 'updateAgentConfig'
2019-07-18 10:46:28,829:140239124489984:INFO:BaseWorkerThread:DrainStatusPoller took 0.941 secs to execute
```
